sudo: true
language: cpp
compiler:
    - gcc
matrix:
    include:
    - os: linux
      addons:
        apt:
            sources:
            - ubuntu-toolchain-r-test
            packages:
            - g++-4.9
            - libboost1.55-all-dev
      env:
      - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9
    - os: osx
before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository ppa:giskou/librocksdb -y  ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -q                            ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install librocksdb -y                ; fi
script:
    - export CXXFLAGS="-std=gnu++11"
    - mkdir build
    - cd build
    - cmake ..
    - make
